cookie:
  expiry_days: 30
  key: test_key
  name: test_name
credentials:
  usernames:
    sakuna:
      email: sakunaj1996@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Sakuna
      last_name: Jayasundara
      logged_in: False # Will be managed automatically
      password: sakuna # Will be hashed automatically
      roles: # Optional
      - admin
      - editor
      - viewer
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Rebecca
      last_name: Briggs
      logged_in: False # Will be managed automatically
      password: def # Will be hashed automatically
      roles: # Optional
      - viewer
# pre-authorized: # Optional
#   emails:
#   - melsby@gmail.com